// Package web embeds the admin UI's built static SPA assets
// (internal/adminui/web/dist/, produced by `make ui-build` from the
// Svelte source under internal/adminui/web/frontend/) into the bridge
// binary. Node and npm are build-time-only dependencies: nothing under
// frontend/ or its node_modules is required, or even present, at
// runtime; the compiled Go binary carries only the static assets
// below.
//
// The "all:" prefix on the embed directive includes files whose name
// begins with "." or "_" (Go's default embed pattern excludes them).
// The built Vite output here does not currently produce such files,
// but "all:" is the correct default for a directory whose contents
// are generated by an external build step this package does not
// control: a future frontend toolchain change that emits a dotfile
// (e.g. a source map manifest) must not silently vanish from the
// embedded bundle.
package web

import "embed"

//go:embed all:dist
var DistFS embed.FS
